name: standalone
automanagedNamespaces: 1
tuningSets:
- name: Sequence
  parallelismLimitedLoad:
    parallelismLimit: 1
steps:
- name: start netowrk metric measurement
  measurements:
    - Identifier: NetworkPerformanceMetrics
      Method: NetworkPerformanceMetrics
      Params:
        action: start 
- name: Start controller and services
  phases:
  - namespaceRange:
      min: 1
      max: 1
      Basename: netperf
    replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: controller-service
      objectTemplatePath: controller-service.yaml
    - basename: controller
      objectTemplatePath: controller-deployment.yaml 
      templateFillMap:
        Protocol: TCP 
        Ratio: 150:150 
        SvcName: controller-service
        Duration: 10
- name: Wait for 5 secs controller to be up
  measurements:
    - Identifier: Wait
      Method: Sleep
      Params:
        duration: 5s
- name: Start worker pods
  phases:
  - namespaceRange:
      min: 1
      max: 1
      Basename: netperf
    replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: worker
      objectTemplatePath: worker-deployment.yaml
      templateFillMap:
        Replicas: 300 
        ControllerIp: controller-service
- name: Wait 1min
  measurements:
    - Identifier: Wait
      Method: Sleep
      Params:
        duration: 1m
- name: Gather
  measurements:
    - Identifier: NetworkPerformanceMetrics
      Method: NetworkPerformanceMetrics
      Params:
        action: gather 
- name: Wait 0min
  measurements:
    - Identifier: Wait
      Method: Sleep
      Params:
        duration: 0m
- name: Removing pods and services
  phases:
  - namespaceRange:
      min: 1
      max: 1
      Basename: netperf
    replicasPerNamespace: 0
    tuningSet: Sequence
    objectBundle:
    - basename: controller-service
      objectTemplatePath: controller-service.yaml
    - basename: controller
      objectTemplatePath: controller-deployment.yaml
      templateFillMap:
        Protocol: TCP 
        Ratio: 150:150 
        SvcName: controller-service
    - basename: worker
      objectTemplatePath: worker-deployment.yaml
      templateFillMap:
        Replicas: 0
        ControllerIp: controller-service

