apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: controller
  labels:
    netperf: controller
spec:
  selector:
    matchLabels:
      netperf: controller
  replicas: 1 #{{.Replicas}}
  template:
    metadata:
      labels:
        netperf: controller
    spec:
      containers:
        - name: controller
          image: netperfbenchmark:0.01
          imagePullPolicy: IfNotPresent
          args:
            - --mode=controller
            - --client-server-pod-ratio=1:1
            - --protocol=udp
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP   
      #     resources:
      #       limits:
      #         cpu: 100m
      #         memory: 100Mi
      #     ports:
      #       - containerPort: 8080
      #         name: metrics
      #     volumeMounts:
      #       - name: logs-volume
      #         mountPath: /var/log
      # volumes:
      #   - name: logs-volume
      #     hostPath:
      #       path: /var/log
