apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    group: network
spec:
  selector:
    svc: {{.Name}}  
  ports:
    - name: rpc
      port: 5002
    - name: metrics
      port: 5010
#      targetPort: 5010
#      nodePort: 8000
