{{$HostNetworkMode := DefaultParam .CL2_USE_HOST_NETWORK_PODS false}}
{{$CpuRequest := DefaultParam .CpuRequest "10m"}}
{{$MemoryRequest := DefaultParam .MemoryRequest "10M"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: netperf
  name: worker
  labels:
    group: network
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        group: network
        name: worker
    spec:
#      hostNetwork: {{$HostNetworkMode}}
      containers:
      - image:  netperfbenchmark:0.03
        name: worker
        imagePullPolicy: IfNotPresent
#        resources:
#          requests:
#            cpu: {{$CpuRequest}}
#            memory: {{$MemoryRequest}}
#        volumeMounts:
#          - name: configmap
#            mountPath: /var/configmap
#          - name: secret
#            mountPath: /var/secret
#      dnsPolicy: Default
#      terminationGracePeriodSeconds: 1
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
#      tolerations:
#      - key: "node.kubernetes.io/not-ready"
#        operator: "Exists"
#        effect: "NoExecute"
#        tolerationSeconds: 900
#      - key: "node.kubernetes.io/unreachable"
#        operator: "Exists"
#        effect: "NoExecute"
#        tolerationSeconds: 900
#      volumes:
#        - name: configmap
#          configMap:
#            name: {{.BaseName}}-{{.Index}}
#        - name: secret
#          secret:
#            secretName: {{.BaseName}}-{{.Index}}
